### ISSUE TITLE
Server Components error when deleting subscription after signup

### ISSUE THREAD

**Issue by chribjel** [gokulkrishh/subs.is#2]
Got this error when trying to delete any subscriptions after signup
![image](https://github.com/gokulkrishh/subs.is/assets/56649743/36a0a7b3-c1f2-436e-971b-7e1c70e568f3)

**Comment by gokulkrishh** [comment]
@chribjel Thanks filling a bug. I tried re-producing it, for me I am able to delete them. Can you logout and try again and see if it works for you?

**Comment by chribjel** [comment]
@gokulkrishh I tried previously, but it didn't work.

It works today though, after i rebooted my computer.

The most accurate way to try to repro this i think would be to open in incognito, sign up for a new user, and then try to delete.

Not sure if the repro is consistent though.

**Comment by gokulkrishh** [comment]
Closing it as its not repo'ble
